### ISSUE TITLE
Build error for ios

### ISSUE THREAD

**Issue by xuanloct4** [QuasarApp/Qt-Secret#101]
I got this issue when build the project for ios on mac. Qt6.3

`/Qt-Secret/src/mini-gmp/CMake/QtStaticCMake/QtStaticCMake.cmake:9: error: By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Qt5Core", but CMake did not find one. Could not find a package configuration file provided by "Qt5Core" with any of the following names: Qt5CoreConfig.cmake qt5core-config.cmake Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set "Qt5Core_DIR" to a directory containing one of the above files.  If "Qt5Core" provides a separate development package or SDK, be sure it has been installed. extensions/Qt-Secret/src/mini-gmp/CMake/QuasarAppCITargets.cmake:123 (include) extensions/Qt-Secret/src/mini-gmp/CMake/QuasarApp.cmake:41 (include) extensions/Qt-Secret/CMakeLists.txt:15 (include)`

**Comment by EndrII** [comment]
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)
