### ISSUE TITLE
Build for Android not working

### ISSUE THREAD

**Issue by jhay06** [QuasarApp/Qt-Secret#102]
Unable to build with android arm64-v8a 

ld: error: undefined symbol: BigInt::BigInt(BigInt const&, int)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced 32 more times

ld: error: undefined symbol: operator-(BigInt, long long)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::generatePairKey(QByteArray&, QByteArray&, QByteArray const&) const)

ld: error: undefined symbol: operator*(BigInt, BigInt const&)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::extEuclid(BigInt, BigInt) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::extEuclid(BigInt, BigInt) const)
>>> referenced 1 more times

ld: error: undefined symbol: BigInt::~BigInt()
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(eulerFunc(BigInt const&, BigInt const&))
>>> referenced 185 more times

ld: error: undefined symbol: operator%(BigInt, long long)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced 7 more times

ld: error: undefined symbol: operator!(BigInt const&)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced 7 more times

ld: error: undefined symbol: BigInt::BigInt()
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::extEuclid(BigInt, BigInt) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::extEuclid(BigInt, BigInt) const)
>>> referenced 9 more times

ld: error: undefined symbol: BigInt::gcd(BigInt const&, BigInt const&)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)

ld: error: undefined symbol: operator==(BigInt const&, long long)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::isMutuallyPrime(BigInt const&, BigInt const&) const)

ld: error: undefined symbol: BigInt::sizeBits() const
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::getBitsSize(BigInt const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::genesisInt(QByteArray const&, int) const)

ld: error: undefined symbol: BigInt::BigInt(long long)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::fromArray(QByteArray const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::randomNumber(bool) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::extEuclid(BigInt, BigInt) const)
>>> referenced 4 more times

ld: error: undefined symbol: BigInt::fromHex(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::fromArray(QByteArray const&) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::genesisInt(QByteArray const&, int) const)

ld: error: undefined symbol: BigInt::getString(int) const
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::toArray(BigInt const&, short) const)

ld: error: undefined symbol: BigInt::longBits() const
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::randomNumber(bool) const)

ld: error: undefined symbol: operator*=(BigInt&, long long)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::randomNumber(bool) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::randomNumber(bool) const)

ld: error: undefined symbol: BigInt::operator++()
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::toPrime(BigInt) const)

ld: error: undefined symbol: BigInt::isPrime(bool) const
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::toPrime(BigInt) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::toPrime(BigInt) const)

ld: error: undefined symbol: operator+=(BigInt&, long long)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::toPrime(BigInt) const)

ld: error: undefined symbol: operator-=(BigInt&, long long)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::toPrime(BigInt) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::generatePairKey(QByteArray&, QByteArray&, QByteArray const&) const)

ld: error: undefined symbol: BigInt::BigInt(char, unsigned int, int)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::randomPrimeNumber(BigInt) const)
>>> referenced by qrsaencryption.cpp
>>>               qrsaencryption.o:(QRSAEncryption::genesisInt(QByteArray const&, int) const)

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [build/release/libQt-Secret_arm64-v8a.so] Error 1
make: *** [sub-src-Qt-Secret-pro-make_first-ordered] Error 2

**Comment by EndrII** [comment]
At Now, I can't fix this issue. May be somebody from community can do this.

**Comment by EndrII** [comment]
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)
