### ISSUE TITLE
using QRSAEncryption signMessage

### ISSUE THREAD

**Issue by jhay06** [QuasarApp/Qt-Secret#103]
Hi any way we can create Sha256withRSA using QRSaencryption ?  is this posible just want to create jwt token without using ssl library

**Comment by paipeng** [comment]
Hello,


can we verify Java-Sha256withRSA using QRSaencryption?

After testing, the "Sha256withRSA" byte array is different.

I have a signautre signed by Java, and want to verify it under Qt-Secret.

Thanks

Regards,

Pai

**Comment by jhay06** [comment]
still no answer u think the project is dead

**Comment by EndrII** [comment]
@jhay06 almost yes. I drop support of this project, because it is not secure. 
I was created a new [library](https://github.com/QuasarApp/easyssl) with support an RSA and ECDSA encryption/authorization algorithms 

The easyssl it is a wrapper of the OpenSSL library. With easy interfaces for Qt. see my [doxygen](https://quasarapp.ddns.net:3031/docs/QuasarApp/easyssl/latest/index.html) documentation and example.

**Comment by jhay06** [comment]
> @jhay06 almost yes. I drop support of this project, because it is not secure. I was created a new [library](https://github.com/QuasarApp/easyssl) with support an RSA and ECDSA encryption/authorization algorithms
> 
> The easyssl it is a wrapper of the OpenSSL library. With easy interfaces for Qt. see my [doxygen](https://quasarapp.ddns.net:3031/docs/QuasarApp/easyssl/latest/index.html) documentation and example.

i see, but im looking for the library which is not dependent on openssl library since im targetting cross platform . hmm , would you mind if i ask a question ? it is related on RSA , what kind of private key and public key does QRSA supports ? i tried pem file , it doesn't work .

**Comment by EndrII** [comment]
> > @jhay06 almost yes. I drop support of this project, because it is not secure. I was created a new [library](https://github.com/QuasarApp/easyssl) with support an RSA and ECDSA encryption/authorization algorithms
> > The easyssl it is a wrapper of the OpenSSL library. With easy interfaces for Qt. see my [doxygen](https://quasarapp.ddns.net:3031/docs/QuasarApp/easyssl/latest/index.html) documentation and example.
> 
> i see, but im looking for the library which is not dependent on openssl library since im targetting cross platform . hmm , would you mind if i ask a question ? it is related on RSA , what kind of private key and public key does QRSA supports ? i tried pem file , it doesn't work .

Your case with crossplatform may be solved using the EASYSSL_STATIC_SSL option. Please see EasySSL [documentation](https://github.com/QuasarApp/easyssl/blob/main/README.md#independet-of-ssl-build) to get more information.
