### ISSUE TITLE
compatibility with OpenSSL etc

### ISSUE THREAD

**Issue by hmoffatt** [QuasarApp/Qt-Secret#104]
Is there a way to do RSA encryption that is compatible with OpenSSL, and other libraries like pycryptodome, such that RSA-encrypted messages can be exchanged with other tools?

**Comment by EndrII** [comment]
Hi,
good idea, but right now I don't have free time to implement ssl format support

**Comment by hmoffatt** [comment]
Thanks for replying... actually I'm not even sure there is a standard format. I looked at some other Python and C++ libraries and couldn't find any real standard except S/MIME and OpenPGP and I didn't see those in the Python libraries either.

**Comment by EndrII** [comment]
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)
