### ISSUE TITLE
Check library gmp

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/Qt-Secret#2]
[GitHub mirror](https://github.com/alisw/GMP)
[GMP wiki](https://ru.wikipedia.org/wiki/GNU_Multi-Precision_Library)

1. Check if it is possible to build this library on windows.
2. Check whether the arithmetic operators for the [c++ wrapper](https://gmplib.org/manual/C_002b_002b-Interface-General.html) of this library are overloaded operators
3. Unsubscribe in the task about the results of the check.

**Comment by EndrII** [comment]
Ответ на вопрос, зачем нужно собирать Qt-Secret в ручную и зачем собирать gmp
1. В с++ существует множество компиляторов, которые реализованы каждый по своему, это значит что структуры результирующих исполняемых файлов тоже могут отличатся так например можно наткнутся на следующую проблему   если ты собрал библиотеку А компиляторам  mingw 64 
а у кого-то проект билдится при помощи компилятора msvc или clang то скорее всего при вызове функций вашей библиотеки человек использующий его столкнется с [segmentation faile](https://ru.wikipedia.org/wiki/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0_%D1%81%D0%B5%D0%B3%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8)
такая ошибка будет возникать не только между видами компиляторов но и между их внутренними версиями например msvc17_64 и msvc15_64 а уж темболие между битавыми разрядностями.
таким образом тебе придется поддерживать сотни сборок одной версии библиотеки. а это очень затратно.
2. При сборки динамически ты зарание привязываешь библиотеку к конкретным версиям зависимостей это значит собранный проект на win10 не запустится на win7.

По этому при распространении библиотек считается правильным подходом отдавать исходный текст и готовую билд систему. Тогда лицо использующее твою библиотеку сам решает первые 2 вопроса, под какую платформу ему собирать и с какими зависимостями.

**Comment by FeZar97** [comment]
GMP library was successfully build on win7.
To do this was used compiler **MinGW** and utility **MSYS**.
Below is a step-by-step guide:
1. After installing **MinGW** and **MSYS**, open the following folder: _../MinGW/msys/1.0/home/"user-name"/_
2. In this directory you must place the folder _gmp-x.x.x_ with source files GMP library downloaded from [https://gmplib.org].
3. In the same directory _../MinGW/msys/1.0/home/"user-name"/_ you need to create a subdirectory _gmpLib_ where the build results will be saved.
4. Then you need open the command shell _../MinGW/msys/1.0/msys.bat_ and inside it open library source directory (`cd _home/"user-name"/gmp-x.x.x_`).
5. Configure the GMP library using the command `./configure --prefix=/home/"user-name"/gmpLib`
6. Run configuration to build (command `make`)
7. Check result of make (command `make check`)
8. Install library (command `make install`)
9. Clean temporary files (`make clean`)
10. At this stage, the ' /home/"user-name"/gmpLib` directory contains folders **include** (contains gmp.h), folder **lib** (contains libgmp.a and libgmp.la). You must copy the files from these folders to the appropriate MinGW folders.
11. Build a dynamic link library: enter command `./configure --prefix=/home/"user-name"/gmp --disable-static --enable-shared`
12. Enter command `make`
13. Enter command `make check`
14. Enter command `make install`
15. Now in folder `/home/"user-name"/gmp` exist folder **bin** with `libgmp-10.dll` and folder **lib** with _libgmp.dll.a_

**Comment by EndrII** [comment]
Thanks for the work.
But the implementation of all these manipulations is not possible to lay on the shoulders of the build system. therefore we will not use gmp.
The question about expanding the digit capacity of numbers is still being postponed.
