### ISSUE TITLE
Check all English text for errors in README.md

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/Qt-Secret#32]
[QtBigInt](https://github.com/QuasarApp/QtBigInt)

[Qt-Secret](https://github.com/QuasarApp/Qt-Secret)

**Comment by EndrII** [comment]
* Go to the document editing mode

![1](https://user-images.githubusercontent.com/12465465/61771062-7d2ae000-adf7-11e9-8ce5-9626ac90f545.png)

* After editing save changes as pull request
 1. Header of changes. for example "fix errors"
 2. Description of changes. for example "i fixed all syntax error of text" 
 3. Click create PR option and select nane  for branch. for example "fixReadme.md"

![2](https://user-images.githubusercontent.com/12465465/61771065-7e5c0d00-adf7-11e9-9f1a-6de690b6aab8.png)

**Comment by Saint-vitamin** [comment]
Hi my name is Dima. And, now i don't understand what i should to do)
