### ISSUE TITLE
Add static methods 

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/Qt-Secret#4]
Add static methods for class [QRSAEncryption](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h) like [QAESEncryption](https://github.com/QuasarApp/Qt-AES/blob/5ecbf59fca7420220550a5d5082251cf23f99ebe/qaesencryption.h)

**Comment by FeZar97** [comment]
resolved successfully
