### ISSUE TITLE
Cmake support

### ISSUE THREAD

**Issue by georgerb** [QuasarApp/Qt-Secret#44]
Hi,
Awesome lib! 
Do you plan to support CMake anytime soon? Qt is encouraging CMake for new projects for a while now.
If you see fit I could create proper CMake files for this lib.

Thank you guys/gals

**Comment by EndrII** [comment]
Hi
I think you're right, qmake is morally outdated, unfortunately now I don’t have time to add cmake support.
I will be very grateful if you do this task.

**Comment by georgerb** [comment]
Deal. My estimate will be 2-3 weekends max to port to cmake.

**Comment by EndrII** [comment]
Thanks, but keep in mind that in order to port qt-secret to cmake you will also need to port the library [Qt-BigInt](https://github.com/QuasarApp/QtBigInt/tree/79645f58d280cc4ca645ad35553dd2bd083c4bb1)

**Comment by georgerb** [comment]
Yep,
I've checked them out, I will submit PRs to each respective submodule.
CMake supports declaring git dependencies so the main project (Qt-Secret) no longer needs git submodules as the main CMake file will check out the git dependencies for us.

**Comment by EndrII** [comment]
I did not know about it, it will be very interesting to see your work.
but I think that submodules will have to be left. 
Because I think that for backward compatibility you need to leave support for the old build system (qmake)

**Comment by georgerb** [comment]
Good point. Let's fork !
