### ISSUE TITLE
LINK : fatal error LNK1181: не удается открыть входной файл "Qt-Secret1.lib".

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/Qt-Secret#45]
LINK : fatal error LNK1181: не удается открыть входной файл "Qt-Secret1.lib".

**Comment by EndrII** [comment]
this seems to be a static build problem under windows
you need to try connecting the library to a static project

**Comment by SecretSilent** [comment]
Hi! I followed instructions in readme file to connect the library to my project. So i tried to do this:

>  * cd yourRepo
>  * git submodule add https://github.com/QuasarApp/Qt-Secret.git 
>  * git submodule update --init --update
>  * Include in your pro file the pri file of Qt-Secret library
>    include($$PWD/Qt-Secret/src/Qt-Secret.pri)
>  * Rebuild yuor project

Trying to rebuild the project i got an error from the subject:
LINK : fatal error LNK1181: не удается открыть входной файл "Qt-Secret1.lib"

So then in Qt-Secret.pri i replaced the line 
win32:LIBS += -L$$Qt_SECRET_LIB_OUTPUT_DIR -lQt-Secret1
on
win32:LIBS += -L$$Qt_SECRET_LIB_OUTPUT_DIR -lQt-Secret

and got the same old error:
LINK : fatal error LNK1181: не удается открыть входной файл "Qt-Secret.lib"

Please, help me to figure it out, what should i do to fix it?

I am using Desktop Qt 5.11.0 MSVC2017 64bit Windows.

**Comment by EndrII** [comment]
Can you send a full rebuild log?

**Comment by SecretSilent** [comment]
> Can you send a full rebuild log?

Do you mean text by assembly console? Attached.
[rebuild-log.txt](https://github.com/QuasarApp/Qt-Secret/files/3635992/rebuild-log.txt)

**Comment by EndrII** [comment]
I do not see the assembly of the library itself.
can you send your PRO and PRI files?

if these files are confidential you can send them to me by mail.

**Comment by SecretSilent** [comment]
> I do not see the assembly of the library itself.
> can you send your PRO and PRI files?
> 
> if these files are confidential you can send them to me by mail.

No, not confidential, in fact my project is empty right now. I wanted to connect it with your library and start writing. But.. something went wrong :)
My only pro file contains this:

> QT       += sql
> QT       -= gui
> 
> TARGET = SLALicenseExt
> TEMPLATE = lib
> 
> DEFINES += SLALICENSEEXT_LIBRARY
> 
> DEFINES += QT_DEPRECATED_WARNINGS
> 
> SOURCES += \
>         slalicenseext.cpp
> 
> HEADERS += \
>         slalicenseext.h \
>         slalicenseext_global.h 
> 
> unix {
>     target.path = /usr/lib
>     INSTALLS += target
> }
> 
> include($$PWD/Qt-Secret/src/Qt-Secret.pri)

**Comment by EndrII** [comment]
I think I understand what the problem is, you connected the library, but did not add it to the assembly, I did not fully describe the connection process.
please see how this library is connected in our gui example.

in the main pro file you need to add the directory with the library as a subproject.
for example, you can see this file [Qt-Secret.Pro](https://github.com/QuasarApp/Qt-Secret/blob/master/Qt-Secret.pro)

* create mainProject.pro
```
TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS += \
           Qt-Secret \
           MyProject
```

* include Qt-Secret in MyProject.pro
Include in your pro file the pri file of Qt-Secret library
include($$PWD/Qt-Secret/src/Qt-Secret.pri)

MyProject - this is your project that you write, it is under the project of the main project that controls the assembly order of libraries.

**Comment by EndrII** [comment]
I just skipped 1 of the steps in the instructions, it's my fault

**Comment by EndrII** [comment]
If you have not worked with subdirs before, you can read about this in this [article](http://blog.mgsxx.com/?p=2425).

**Comment by EndrII** [comment]
I fixed my include [instruction](https://github.com/QuasarApp/Qt-Secret/blob/master/README.md) of Qt-Secret
