### ISSUE TITLE
Can't get it to install

### ISSUE THREAD

**Issue by ssaguiar** [QuasarApp/Qt-Secret#48]
When I try to get the lib installed, as described in instructions, I get this:

git submodule update --init --recursive
Submodule 'src/Qt-AES' (https://github.com/QuasarApp/Qt-AES.git) registered for path 'src/Qt-AES'
Submodule 'src/mini-gmp' (https://github.com/QuasarApp/mini-gmp.git) registered for path 'src/mini-gmp'
Cloning into '/home/ssaguiar/Qt-Secret/src/Qt-AES'...
Cloning into '/home/ssaguiar/Qt-Secret/src/mini-gmp'...
Submodule path 'src/Qt-AES': checked out '61876c7e0639eaca5588dab24c32caeae6573331'
Submodule path 'src/mini-gmp': checked out '79645f58d280cc4ca645ad35553dd2bd083c4bb1'
ssaguiar@DESKTOP-55C2EA1:~/Qt-Secret$ qmake -r
qmake: could not find a Qt installation of ''

Any clues?

Thanks

**Comment by EndrII** [comment]
try "qmake -r Qt-Secret.pro"

**Comment by EndrII** [comment]
do you have qt installed?

**Comment by EndrII** [comment]
I updated build instruction.

---

# Build

 * git clone https://github.com/QuasarApp/Qt-Secret.git
 * cd Qt-Secret
 * git submodule update --init --recursive
 * sudo apt install qt5-default
 * qmake -r DEFINE+=WITHOUT_GUI Qt-Secret.pro 
  > DEFINE+=WITHOUT_GUI fot build without gui example, if you want build gui example remove this line. For build the gui example you need to install qml controls 2 in you os. Try **sudo apt install qml-module-qtquick-controls2**
 * make -j8
 * make test #(for testing)
