### ISSUE TITLE
QRSAEncryption::randomNumber issue

### ISSUE THREAD

**Issue by itimmyy** [QuasarApp/Qt-Secret#50]
There is a strange place in function `INTINT QRSAEncryption::randomNumber(bool fullFill)` . Variable `INT res{1};` initiated with 1, and it is good, but after that there is `res *= rand() % std::numeric_limits<int>::max();` and if `rand()` return 0, this function stuck forever. So, is it wrong behaviour in my environment, or is it bug? Best regards.

**Comment by EndrII** [comment]
Thanks for your report about this error

I propose to fix it on:
```cpp
    res *= rand() % (std::numeric_limits<int>::max() - 1) + 1;
```

do you agree with that?
if you have more interesting solutions, you can issue a pull request with a correction.

**Comment by EndrII** [comment]
@FeZar97 You can join the discussion.

**Comment by itimmyy** [comment]
@EndrII Yes, it seems quite good. Thank you. Best wishes.
