### ISSUE TITLE
'INT' : redefinition error

### ISSUE THREAD

**Issue by cristiulian** [QuasarApp/Qt-Secret#52]
I'm getting the following compile error in QT for Windows.
qrsaencryption.h:21: error: C2371: 'INT' : redefinition; different basic types

The INT type is already defined somewhere else:
C:\Program Files (x86)\Windows Kits\8.1\include\shared\minwindef.h:176

It should be  a good idea to guard your code in a namespace.

**Comment by EndrII** [comment]
You are absolutely right,
I will take up this task next week, because now there is no time for this.
If you are ready to solve this problem yourself, put **qrsaencription.h and qrsaencription.cpp** in the **QtSecretRSA** namespace and create the pull request.

 I will be very grateful to you.
