### ISSUE TITLE
Invalid key pairs generated

### ISSUE THREAD

**Issue by cristiulian** [QuasarApp/Qt-Secret#53]
I'm using the code snippet below.
testKeyPair returns false.
I've taken testKeyPair from the private methods, as I needed to find out why the signMessage didn't work.

QByteArray pub, priv;

QRSAEncryption e;
e.generatePairKey (pub, priv, QRSAEncryption :: Rsa :: RSA_128);

if(e.testKeyPair(pub, priv))
    qDebug() << "Pair valid";
else
    qDebug() << "Pair invalid";

**Comment by EndrII** [comment]
Run tests in your pc.

* git clone https://github.com/QuasarApp/Qt-Secret.git
* open in qt creator Qt-Secret.pro
* run Qt-SecretTests

---
or install [cqtdeployer](https://github.com/QuasarApp/CQtDeployer/releases) and run in cmd 
* cd Qt-Secret
* my/qmake.exe -r Qt-SecretTests
* my/make.exe 
* my/make.exe test
what happens after running the tests?

**Comment by EndrII** [comment]
Try now, maybe your issue is fixed.(see #54 )
I think encryption and decryption cannot work because  your system replaces the 'INT' type of the qt-secret library with the 'INT' type of the system.

**Comment by ipostanogov** [comment]
[This](https://github.com/QuasarApp/Qt-Secret/tree/77313e3b52157ebe0608a4c269798ddb2a3cf577#signature-and-verification-of-the-message-signature) sample does not work either. 

It looks that it works only if the key size is the same as the size specified [here](https://github.com/QuasarApp/Qt-Secret/blob/77313e3b52157ebe0608a4c269798ddb2a3cf577/src/Qt-RSA/qrsaencryption.h#L53).

**Comment by EndrII** [comment]
> [This](https://github.com/QuasarApp/Qt-Secret/tree/77313e3b52157ebe0608a4c269798ddb2a3cf577#signature-and-verification-of-the-message-signature) sample does not work either.
> 
> It looks that it works only if the key size is the same as the size specified [here](https://github.com/QuasarApp/Qt-Secret/blob/77313e3b52157ebe0608a4c269798ddb2a3cf577/src/Qt-RSA/qrsaencryption.h#L53).

You are right, Already corrected. see #57
