### ISSUE TITLE
get key string that works with openssl

### ISSUE THREAD

**Issue by CodeCrafter912** [QuasarApp/Qt-Secret#55]
Hi,

Is it possible to convert the keys to the format openssl needs (starting with '-----BEGIN PUBLIC KEY-----' and ending with '-----END PUBLIC KEY-----')?
I've tried to do that for some hours now, but I'm completely stuck.

Regards
Dorian

**Comment by EndrII** [comment]
Hi.  

Yes, I think it’s possible, the only thing is that QtSecret doesn’t currently have a method for importing and exporting such a key type.  Tomorrow I will try to understand this issue in detail.

**Comment by FeZar97** [comment]
> Is it possible to convert the keys to the format openssl needs (starting with '-----BEGIN PUBLIC KEY-----' and ending with '-----END PUBLIC KEY-----')?

Hi, Dorian
Please specify, what you mean by key storage format. Only start and end with specified flags, or you need full compatibility with the openssl key storage format?

**Comment by CodeCrafter912** [comment]
I would like to be able to decrypt a string which was encrypted using Qt-Secret with openssl in php. So - full compatibilty I guess.

**Comment by EndrII** [comment]
@CodeCrafter912
We can soon add support for openssl keys (export and import), but encryption and decryption should be performed by one library. Later we will try to add full compatibility with openssl, but this will take some time.

Do you urgently need full compatibility?

**Comment by CodeCrafter912** [comment]
For now, it would be enough for me to know if / how it is possible to convert a publickey generated with openssl into a key that works with Qt-Secret manually. Or isn't that easily possible?

**Comment by EndrII** [comment]
Yes, the conversion's implementetion is fast, it will be ready within a couple of days. As for encryption and decryption, it will take longer

**Comment by CodeCrafter912** [comment]
To be honest, I don't know a lot about the math behind RSA. But as I understand you, converting the keys is not all it takes to encrypt something with Qt-Secret that openssl can decrypt, or is it actually that simple? (that's what I thought)

**Comment by EndrII** [comment]
> To be honest, I don't know a lot about the math behind RSA. But as I understand you, converting the keys is not all it takes to encrypt something with Qt-Secret that openssl can decrypt, or is it actually that simple? (that's what I thought)

All right.  It's not so simple, in order to achieve full compatibility between libraries, we need to change the encryption logic.  It won `t be soon.
 So I recommend you use openssl in qt and in php.  Then everything is guaranteed to work for you.
 As I said at the moment, it is important that one library is engaged in encryption and decryption.

**Comment by CodeCrafter912** [comment]
Ok, then I'm going to do it like that.
Thanks for your effords!

**Comment by EndrII** [comment]
This library not support ssl keys.

**Comment by MCredbear** [comment]
> This library not support ssl keys.

Sorry, but I have the request of using ssl keys,too. As I have tried many Qt wrapped openssl libraries, I find a problem: They use different versions of openssl, though they provide includes, it is strange to let my project consists a standalone openssl, and this always causes build faults. Could you continue this process? Thanks.
