### ISSUE TITLE
Loading keys from file

### ISSUE THREAD

**Issue by radimkohout** [QuasarApp/Qt-Secret#63]
Hi,
is there any way to use keys generated by Qt-Secret, that I have load from files?
Thanks
Radim Kohout

**Comment by EndrII** [comment]
hi,take a look a t#55.This is request of  support OpenSSL keys. But as I understand you want to encrypt and decrypt information with Qt-Secret only. If it is true then you can read/write keys into files with QFile.

**Comment by EndrII** [comment]
Later I will add save and write methods to Qt-Secret

**Comment by radimkohout** [comment]
But how to parse loaded keys from files into Qt-Secret(using RSA)?

**Comment by EndrII** [comment]
okey. I will add a way to get the key type from a byte array. With any luck today will be ready.

see PR #64

**Comment by EndrII** [comment]
To get a description of the key, use:
``` cpp
    /**
     * @brief getKeyRsaType - return the key RSA type.
     * @param key - public or private RSA key.
     * @return QRSAEncryption::Rsa
     */
    static QRSAEncryption::Rsa getKeyRsaType(const QByteArray& key);
```
