### ISSUE TITLE
cannot find -lQt-Secret1, cannot find -lQtBigInt6

### ISSUE THREAD

**Issue by DmitryDemidov80** [QuasarApp/Qt-Secret#73]
Hi!
I downloaded src Qt-Secret, git submodule update --init --recursive, etc...
I included in my .pro-file
`include($$PWD/Qt-Secret/src/Qt-Secret.pri)`
but get errors:
cannot find -lQt-Secret1 and cannot find -lQtBigInt6

I try to build Qt-Secret-GUI.pro but get same error

MinGW, Qt 5.14.2
What i'm doing wrong?
Thanks!

**Comment by EndrII** [comment]
It looks like Qt-Secret is not built.
You can show me your PRO files?
* Main PRO file with subdirectories (this file should include Qt_secret first and then your project) 
* And you project pro file 

##  example of project structure:
### Main Pro File :
``` qmake 
TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS += \
           Qt-Secret \
           MyProject \

```

### You MyProject.pro
``` qmake
 CONFIG += c++11


SOURCES += \
        main.cpp \

include($$PWD/../src/Qt-Secret.pri)


```

## For more information see :
* [Qt-Secret.pro](https://github.com/QuasarApp/Qt-Secret/blob/master/Qt-Secret.pro) (mainPro)
* [src/Qt-Secret.pro](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-Secret.pro) (qtSecret library pro file)
* [Qt-Secret-GUI.pro](https://github.com/QuasarApp/Qt-Secret/blob/master/Qt-Secret-GUI/Qt-Secret-GUI.pro) (external application using qt-secretlibrary)

**Comment by DmitryDemidov80** [comment]
I don't have the main .pro-file

My .pro-file:
`
QT       += core gui serialport network
CONFIG += c++17
VERSION = 2.0.0
DEFINES += APP_VERSION=\\\"$$VERSION\\\"
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
DEFINES += QT_DEPRECATED_WARNINGS
QMAKE_LFLAGS_RELEASE += -static -static-libgcc

include($$PWD/Qt-Secret/src/Qt-Secret.pri)

include(Logger/Logger.pri)
include(QtXlsx/src/xlsx/qtxlsx.pri)
include(updater_app/updater_app.pri)

TARGET = myapp
DESTDIR = ../qtbin/myapp

SOURCES += here *.cpp

HEADERS += here *.h

FORMS += here all forms
`

I try to build for example Qt-Secret-GUI.pro but failed.
OS: Windows 10 64 bit,

**Comment by EndrII** [comment]
I still think that you will need main.pro, since this is the most convenient way to assemble all system components from a single file.

**Comment by DmitryDemidov80** [comment]
Thanks!

**Comment by EndrII** [comment]
do you manage to build Qt-Secret (main project) from QtCreator?

**Comment by DmitryDemidov80** [comment]
Yes, i can build Qt-Secret from Qt Creator.
I have to remanage project to create MainProject.pro-file and add to Qt-Secret and my project as subdirs.

**Comment by EndrII** [comment]
Right. If this solves your problem, please close this issue.
