### ISSUE TITLE
bigint.h file not found

### ISSUE THREAD

**Issue by sonichy** [QuasarApp/Qt-Secret#79]
Linux Deepin:
qrsaencryption.h#L19
#include <bigint.h> // bigint.h file not found
typedef BigInt INT; // unknown type name 'BigInt'

QRSAEncryption e(QRSAEncryption::Rsa::RSA_2048);
e.generatePairKey(pubKey.toUtf8(), key.toUtf8()); // no matching member function for call to 'generatePairKey'
QString encSecKey = e.encode(key.toUtf8(), pubKey.toUtf8());

Where is MODULUS of RSA ?

**Comment by EndrII** [comment]
Hi, 
Show me please your Qt-Secret folder.
it looks like you don't have all the submodules

try this 
``` bash
git submodule update --init --recursive 
```

**Comment by sonichy** [comment]
For simple use, I only copy qrsaencryption.h, qrsaencryption.cpp, qtsecret_global.h to the root of my project.

**Comment by EndrII** [comment]
@sonichy, i andustend you, but The Qt-Secret working with big int library. Best solution it is include Qt-Secret using cmake or qmake build sustems.   

## For qmake projects 

 * cd yourRepo
 * git submodule add https://github.com/QuasarApp/Qt-Secret.git # add the repository of Qt-Secret into your repo like submodule
 * git submodule update --init --recursive
 * Add to the list of libraries for the Qt-Secret assembly. For example, you can create Main.Pro in which connect Qt-Secret and your project.pro files as subprojects.
 
 **Main.pro:**
``` qmake
TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS += \
           Qt-Secret \
           MyProject
```
 * Include in your MyProject.pro file the pri file of Qt-Secret library
 ``` qmake
 include($$PWD/../Qt-Secret/src/Qt-Secret.pri)
 ```
 * Rebuild your project

 ### For cmake projects
 
 * cd yourRepo
 * git submodule add https://github.com/QuasarApp/Qt-Secret.git # add the repository of Qt-Secret into your repo like submodule
 * git submodule update --init --recursive
 * Include in your CMakeLists.txt file the main CMakeLists.txt file of Qt-Secret library
  ``` cmake
    add_subdirectory(Qt-Secret)
    target_link_libraries(MyBinary PUBLIC Qt-Secret)
  ```
 * Rebuild your project


But If you want include only one cpp file then you need to include [BigInt](https://github.com/QuasarApp/QtBigInt) source code

**Comment by sonichy** [comment]
I thought it was botan bigint ...

**Comment by EndrII** [comment]
If you managed to solve this issue, please close it.

**Comment by sonichy** [comment]
In fact, i want to change these python to Qt
```
pubKey = '010001'
modulus = '00e0b509f6259df8642dbc35662901477df22677ec152b5ff68ace615bb7b725152b3ab17a876aea8a5aa76d2e417629ec4ee341f56135fccf695280104e0312ecbda92557c93870114af6c9d05c4f7f0c3685b7a46bee255932575cce10b424d813cfe4875d3e82047b97ddef52741d546b8e289dc6935b3ece0462db0a22b8e7'

def rsaEncrypt(text, pubKey, modulus):
    text = text[::-1]
    rs = int(text.encode('hex'), 16)**int(pubKey, 16)%int(modulus, 16)
    return format(rs, 'x').zfill(256)
```
