### ISSUE TITLE
windeployqt || Unable to run exe

### ISSUE THREAD

**Issue by meadlai** [QuasarApp/Qt-Secret#81]
Thanks to this project, I can use the RSA and AES very easy.

I have created a main project which can be built good, debug good, I can run the Qt-Secret-GUI.exe in the QTCreator or debug model.

I am running it in windows 10, Microsoft Visual Studio 2019, configure with msvc2019_64
So I didn't run the following make command, any alternative cmd I can run in windows? thanks.
```
make -j8
make test #(for testing)
```

Here is my Main.pro
```
TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS += \
           Qt-Secret \
           AppLoader
```

But I can't run the exported exe, I run following cmd to collect all dll files, then I open the AppLoader.exe, it can't find the QT-Secret1.dll and QtBigInt6.dll. Is there anything missing?
Thank you very much.

C:\Qt\5.15.2\msvc2019_64\bin\windeployqt D:\robot\exe\login\output\AppLoader\debug

**Comment by meadlai** [comment]
Sorry, I found the dll in following folder, many thanks.

\Qt-Secret\src\mini-gmp\src\build\release\QtBigInt6.dll
Qt-Secret\src\build\release\Qt-Secret1.dll

**Comment by meadlai** [comment]
Sorry, I found the dll in following folder, many thanks.

\Qt-Secret\src\mini-gmp\src\build\release\QtBigInt6.dll
Qt-Secret\src\build\release\Qt-Secret1.dll

**Comment by EndrII** [comment]
@meadlai try use [cqtdeployer](https://github.com/QuasarApp/CQtDeployer). this tool have options for automation search all libraries.

```
cqtdeployer -bin your.exe -libDir /root/of/the/your/project -recursiveDepth 5 -qmake path/to/used/qmake.exe
```
but on windows cqtdeployer worked for release only. so if you want to deploy the debug application then  use the windeployqt tool.
