### ISSUE TITLE
Add description to methods

### ISSUE THREAD

**Issue by Oleg-designer** [QuasarApp/Qt-Secret#87]

**Comment by Oleg-designer** [comment]
Add please description to arguments of next methods: 

- [QRSAEncryption](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L61)
- [encode](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L95)
- [decode](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L106)
- [signMessage](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L117)
- [checkSignMessage](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L127)
- [save](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L158)
- [load](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L167)
- [signMessage](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L210)
- [generatePairKey](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L90)
- [generatePairKey](https://github.com/QuasarApp/Qt-Secret/blob/master/src/Qt-RSA/qrsaencryption.h#L75)

**Comment by EndrII** [comment]
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)
