### ISSUE TITLE
Adding RSA benchmarking

### ISSUE THREAD

**Issue by Benjamin-Loison** [QuasarApp/Qt-Secret#93]
I run both following RSA algorithms on a Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz
- https://github.com/QuasarApp/Qt-Secret#encryption-and-decryption-of-messages
- https://github.com/QuasarApp/Qt-Secret#signature-and-verification-of-the-message-signature

Here are my benchmarking (I would have appreciated to find some on the GitHub so I participate):

RSA in seconds

|key size|2048|3072|4096|6144|8192|
|--------|:----:|:----:|:-----:|:----:|:-----:|
|genPairKey (random process)|2.119|6.974|44.000|31.384|243.044|
|encode|0.062|0.170|0.437|1.489|3.470|
|decode|0.096|0.286|0.745|2.449|5.651|
|sign|1.668|5.503|13.226|44.422|104.119|
|checkSign|2.906|10.014|23.420|75.711|262.077|

**Comment by EndrII** [comment]
Thanks you. may be you can create a pull request with your bench tool ?

**Comment by Benjamin-Loison** [comment]
I haven't any bench tool I just used: qDebug() << QTime::currentTime().toString("hh:mm:ss,zzz") << " ID 0";
In the README algorithms sorry about that ^^'

**Comment by EndrII** [comment]
So just create a subproject of the main project that will be use this code. Else cannot to add your benchmark test results without benchmark tool.

**Comment by pH-Valiu** [comment]
How big was the data you encoded?

**Comment by Benjamin-Loison** [comment]
> How big was the data you encoded?

The data was `test message`. You can find the whole code [here](https://github.com/Benjamin-Loison/Travian-blockchained/blob/10fd8c3df6198bb5f10b92ea53f481e4179cdfb7/main.cpp#L35-L88).

**Comment by EndrII** [comment]
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)
