### ISSUE TITLE
cannot find -lQt-Secret1 and cannot find -lQtBigInt6 but I`ve do everything with guide

### ISSUE THREAD

**Issue by Jimbo02** [QuasarApp/Qt-Secret#94]
Hi, 
I have added master.pro with subdirs
`TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS += \
          auth \
          Qt-Secret \
auth.file = "./auth/auth.pro"`

and `include($$PWD/../Qt-Secret/src/Qt-Secret.pri)` in my project file(auth.pro)

What did I wrong? Thank you.

**Comment by EndrII** [comment]
hi.
you close this issue. You solve your trouble ?

**Comment by Jimbo02** [comment]
> hi.
> you close this issue. You solve your trouble ?

Hi. Yes. I created new subdirs project and made same moves.
