### ISSUE TITLE
QT6 can not use

### ISSUE THREAD

**Issue by huoyuanfan** [QuasarApp/Qt-Secret#98]
i cant use it on QT6，how can i do it

**Comment by pH-Valiu** [comment]
Try pulling it in Qt directly from github via File/New Project/Import Project/Git Clone and then check mark the "recursive" button.
What have you tried until now?

**Comment by EndrII** [comment]
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)
